name: "CICD for Python Application"
on: push
jobs:
  main-cicd:
    runs-on: ubuntu-latest
    container: ago29/gitlab-base-image
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Linting-uses
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
      # - name: Linting
      #   run: |
      #     ls -la
      #     pre-commit run --all-files
