name: "CICD for Python Application"
on: workflow_dispatch
jobs:
  lint:
    runs-on: ubuntu-latest
    container: ago29/gitlab-base-image
    steps:
      - name: Linting
        run: |
          echo -n "Running pre-commit"
          pre-commit run --all-files
