name: "CICD for Python Application"
on: push
jobs:
  main-cicd:
    runs-on: ubuntu-latest
    container: ago29/gitlab-base-image
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Linting
        run: |
          pwd
          ls -la
          pre-commit install --install-hooks
          pre-commit run --all-files
